schema: graphql/pokedex_schema.json
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://graphql-pokeapi.graphcdn.app/graphql
      headers:
        user-agent: JS GraphQL
      introspect: false
