name: PR Build and Test

on: pull_request

jobs:
  lint_kotlin:
    name: 'Lint Kotlin'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Lint Check
        run: ./gradlew lintKotlin

  build_artifacts:
    name: 'Build Artifacts'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Build APKs
        run: ./gradlew build

      - name: Upload Release APK
        uses: actions/upload-artifact@v4
        with:
          name: 'pokedex-release-pr-${{ github.event.number }}-v${{ github.run_id }}.apk'
          path: 'app/build/outputs/apk/release/*.apk'
          if-no-files-found: 'error'

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: 'pokedex-debug-pr-${{ github.event.number }}-v${{ github.run_id }}.apk'
          path: 'app/build/outputs/apk/debug/*.apk'
          if-no-files-found: 'error'
